const Discord = require("discord.js");
module.exports.run = async (client, message, args) => {
  const responses = [
		            "3-d
            3x5
            5lineoblique
            acrobatic
            alligator
            alligator2
            alphabet
            avatar
            banner
            banner3-D
            banner3
            banner4
            barbwire
            basic
            bell
            big
            bigchief
            binary
            block
            bubble
            bulbhead
			calgphy2
			caligraphy
			catwalk
			chunky
			coinstak
			colossal
			computer
			contessa
			contrast
			cosmic
			cosmike
			cricket
			cursive
			cyberlarge
			cybermedium
			cybersmall
			diamond
			digital
			doh
			doom
			dotmatrix
			drpepper
			eftichess
			eftifont
			eftipiti
			eftirobot
			eftitalic
			eftiwall
			eftiwater
			epic
			fender
			fourtops
			fuzzy
			goofy
			gothic
			graffiti
			hollywood
			invita
			isometric1
			isometric2
			isometric3
			isometric4
			italic
			ivrit
			jazmine
			jerusalem
			katakana
			kban
			larry3d
			lcd
			lean
			letters
			linux
			lockergnome
			madrid
			marquee
			maxfour
			mike
			mini
			mirror
			mnemonic
			morse
			moscow
			nancyj-fancy
			nancyj-underlined
			nancyj
			nipples
			ntgreek
			o8
			ogre
			pawp
			peaks
			pebbles
			pepper
			poison
			puffy
			pyramid
			relief
			relief2
			rev
			roman
			rot13
			rounded
			rowancap
			rozzo
			runic
			runyc
			sblood
			script
			serifcap
			shadow
			short
			slant
			slide
			slscript
			small
			smisome1
			smkeyboard
			smscript
			smshadow
			smslant
			smtengwar
			speed
			stampatello
			standard
			starwars
			stellar
			stop
			straight
			tanja
			tengwar
			term
			thick
			thin
			threepoint
			ticks
			ticksslant
			tinker-toy
			tombstone
			trek
			tsalagi
			twopoint
			univers
			usaflag
			wavy
			weird"
	];
	var embedcolor = '#' + ("000000" + Math.random().toString(16).slice(2, 8).toUpperCase()).slice(-6);
	const embed = new Discord.RichEmbed()
	.setDescription('Random Greetings!')
	.setThumbnail(client.user.displayAvatarURL)
	.addField("Greetings!", '' + message.author.toString() + ' umm.. ' + responses[Math.floor(Math.random() * responses.length)])
        .setColor(embedcolor)
	.setFooter("Powered by Uzumaki-clan")
	message.channel.send({embed: embed})
}

module.exports.help = {
    name: "ascii-list"
}
